### ISSUE TITLE
Missing quotation marks

### ISSUE THREAD

**Issue by astania** [learn-co-curriculum/phase-1-using-json-server-and-postman#2]
Hello! Me being annoying again. In one of your JSON code examples, you reference "outer quotations" but I don't think you've actually included those in the code example. Here's what you have:

{ "name": "Tesla", "occupation": "Inventor" }
The data above is a String, but you can see that it contains what looks like key/value pairs. Notice that the keys and values are both wrapped in quotes while other characters, {, }, and :, are not. This is required syntax for JSON. All text-based data, even keys, must be wrapped in quotes within the larger String. Numbers are the only exception to this.

Since you reference outer quotes, shouldn't it be written like:

"{ "name": "Tesla", "occupation": "Inventor" }"

I could be totally wrong, but this is how I interpreted this lesson. Thanks for all your hard work!

**Comment by ihollander** [comment]
Hi @astania - thanks for flagging this issue, your feedback is always appreciated 😄 We'll get this fixed. If you'd like to know more about this particular issue, here's an explanation:

This looks to be an issue with the markdown code formatting that is used to get the proper syntax highlighting in Canvas. In Markdown, you're able to write blocks of code formatted for specific languages using something known as [Fenced Code Blocks](https://www.markdownguide.org/extended-syntax/#syntax-highlighting). They look like this:

What's written in Markdown:

~~~
```json
{ "hello": "world!" }
```
~~~

With syntax highlighting:

```json
{ "hello": "world!" }
```

Since quotes around the outside of a JSON object aren't valid JSON, this code snippet wouldn't render correctly:

Markdown:

~~~
```json
'{ "hello": "world!" }'
```
~~~

Syntax highlighting:

```json
'{ "hello": "world!" }'
```

Instead, we need to label this as regular a regular text block so that we can demonstrate that JSON is just a specially-formatted string:

Markdown:

~~~
```text
'{ "hello": "world!" }'
```
~~~

Syntax highlighting:

```text
'{ "hello": "world!" }'
```
